openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /technicalBooks:
    get:
      operationId: getTechnicalbooks
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /environmentVariables:
    get:
      operationId: getEnvironmentvariables
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
